name: build container
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Login to Heroku Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: ${{ secrets.heroku_username }}
        password: ${{ secrets.heroku_password }}
    - name: Push to Heroku Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.heroku.com/delete_shiritori/web
