name: build container
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Change the working directory to client
      run: |
        cd client
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Cache Node
      id: node-cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: |
        npm install
    - run: |
        CI=true npm run build
    - name: Change the working directory to server
      run: |
        cd ../server
    - name: Login to Heroku Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: ${{ secrets.heroku_username }}
        password: ${{ secrets.heroku_password }}
    - name: Push to Heroku Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: registry.heroku.com/delete_shiritori/server
