name: client check
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.js'
  workflow_dispatch:

jobs:
  client-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Cache Node
      id: node-cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: |
        npm install
      working-directory: ./client
    - run: |
        CI=true npm test
      working-directory: ./client
