name: server check
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  server-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Cache pip
      id: pip-cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install poetry
      run: |
        python -m pip install poetry
        poetry config virtualenvs.in-project true
    - name: Cache dependencies
      id: dependencies-cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-dep-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-dep-
      working-directory: ./server
    - name: Install dependencies
      run: poetry install
      working-directory: ./server
    - name: Lint with flake8
      run: |
        poetry run flake8 ./delete_shiritori ./tests --count --show-source --statistics
      working-directory: ./server
    - name: Lint with black
      run: |
        poetry run black ./delete_shiritori ./tests --check --diff
      working-directory: ./server
    - name: Lint with mypy
      run: |
        poetry run mypy ./delete_shiritori ./tests --pretty
      working-directory: ./server
    - name: Lint with isort
      run: |
        poetry run isort ./delete_shiritori ./tests --check-only
      working-directory: ./server
    - name: Test with pytest
      run: |
        poetry run pytest tests
      working-directory: ./server
